create table Futurama (name char(20), voiced_by char(40), description char(200), first_appearance char(40));

insert into Futurama values('Philip J. Fry','Billy West','Protagonist, from the 20th Century. Delivery boy. Many times great-uncle and great-grandfather to Professor Farnsworth.','Space Pilot 3000');
insert into Futurama values('Turanga Leela','Katey Sagal','Mutant cyclops. Captain of the Planet Express Ship. Love interest of Fry.','Space Pilot 3000');
insert into Futurama values('Bender Bending Rodriguez','John DiMaggio','A kleptomaniacal, cigar-smoking, heavy-drinking robot who is Frys best friend. Built in Tijuana, Mexico, he is the Planet Express Ships cook.','Space Pilot 3000');
insert into Futurama values('Amy Wong','Lauren Tom','Chinese-Martian intern at Planet Express. Spouse of Kif Kroker.','The Series Has Landed');
insert into Futurama values('Hermes Conrad','Phil LaMarr','Bureacraft and aaccountant of Planet Express.','The Series Has Landed');
insert into Futurama values('Professor Farnsworth','Billy West','Many times great-nephew and great-grandchild of Fry. CEO and owner of Planet Express delivery company. Tenured professor of Mars University.','Space Pilot 3000');
insert into Futurama values('Doctor John Zoidberg','Billy West','Alien from Decapod 10. Planet Express staff doctor and steward. Has a medical degree and Ph.D in art history.','The Series Has Landed');
insert into Futurama values('Lord Nibbler','Frank Welker','Nibblonian ambassador to Earth. Poses as Leelas pet.','Loves Labours Lost in Space');
insert into Futurama values('Zapp Brannigan','Billy West','25-star General in the Democratic Order of Planets (D.O.O.P.), Captain of the Nimbus flagship and head of the D.O.O.P. army.','Loves Labours Lost in Space');
insert into Futurama values('Kif Kroker','Maurice LaMarche','Amphibiosion. Fourth Lieutenant of the Nimbus spaceship. Spouse of Amy Wong.','Loves Labours Lost in Space');
insert into Futurama values('Mom','Tress MacNeille','Antagonist. Owner of MomCorp, and Professor Farnsworths former lover.','A Fishful of Dollars');
insert into Futurama values('Headless Body of Agnew','Maurice LaMarche','The headless body of Spiro Agnew, former Vice President of the United States of America. Incumbent Vice President of Earth and aide to Richard Nixons Head.','Space Pilot 3000');
insert into Futurama values('Boxy','n/a','A basic robot only able to communicate by beeping. Assistant to Calculon.','I, Roommate');
insert into Futurama values('Brain Slugs','n/a','Small, parasitic aliens who attach themselves to the heads of intelligent beings and control them.','A Head in the Polls');
insert into Futurama values('Brain Spawn','various','A race of flying telepathic brains, who feed off knowledge and wish to destroy other sentient lifeforms.','A Clone of My Own');
insert into Futurama values('Calculon','Maurice LaMarche','Famous actor robot. Star of TV drama "All My Circuits".','I, Roommate');
insert into Futurama values('The Crushinator','Maurice LaMarche','Robot daughter of human hydroponic farmer on the Moon. Mother of Benders child, Junior.','The Series Has Landed');
insert into Futurama values('Father Changstein-El-Gamal','David Herman','Leader of First Amalgamated Church.','Godfellas');
insert into Futurama values('Chanukah Zombie','Mark Hamill','Undead personification of Chanukah. Part of the "Holiday Trinity".','Benders Big Score');
insert into Futurama values('Clamps','Maurice LaMarche','An unstable member of the Robot Mafia, obsessed with using the clamps that form his hands.','Bender Gets Made');
insert into Futurama values('Dwight Conrad','Bumper Robinson/Phil LaMarr','Son of Hermes and LaBarbara Conrad.','The Route of All Evil');
insert into Futurama values('LaBarbara Conrad','Dawnn Lewis','Wife of Hermes Conrad, mother of Dwight Conrad. Former wife of Barbados Slim.','A Flight To Remember');
insert into Futurama values('Donbot','Maurice LaMarche','Head of the Robot Mafia.','Bender Gets Made');
insert into Futurama values('Elzar','John DiMaggio','A renowned Neptunian chef.','My Three Suns');
insert into Futurama values('Cubert Farnsworth','Kath Soucie','Professor Farnsworths clone.','A Clone of My Own');
insert into Futurama values('Flexo','John DiMaggio','A Bending Unit from the same assembly line as Bender. Almost identical in appearance, voice and personality.','The Lesser of Two Evils');
insert into Futurama values('Al Gores Head','Al Gore','Former Vice President of the United States of America. Member of the "Vice Presidential Action Rangers", and First Emperor of the Moon.','Anthology of Interest I');
insert into Futurama values('Gypsy-bot','Tress MacNeille','Robotic fortune-telling machine.','My Three Suns');
insert into Futurama values('Stephen Hawking','Stephen Hawking','Member of the "Vice Presidential Action Rangers", and celebrated scientist.','Anthology of Interest I');
insert into Futurama values('Hedonismbot','Maurice LaMarche','Robotic personification of Hedonism.','Crimes of the Hot');
insert into Futurama values('Horrible Gelatinous Blob','Maurice LaMarche','A large, translucent and acidic alien.','The Series Has Landed');
insert into Futurama values('Hyperchicken','Maurice LaMarche','A successful Hyperchicken lawyer.','Brannigan, Begin Again');
insert into Futurama values('Hypnotoad','n/a','A large toad with oscillating, multicoloured eyes. When hypnotising people, it emits a buzzing noise known as "Angry Machine"','The Day the Earth Stood Stupid');
insert into Futurama values('Kwanzaabot','Coolio','Robotic personification of Kwanzaa. Part of the "Holiday Trinity".','A Tale of Two Santas');
insert into Futurama values('Lrrr','Maurice LaMarche','Ruler of Omicron Persei 8. Husband of Ndnd.','When Aliens Attack');
insert into Futurama values('Linda van Schoonhoven','Tress MacNeille','Co-anchor of √2 News, with Morbo.','A Big Piece of Garbage');
insert into Futurama values('Hattie McDoogal','Tress MacNeille','A twice-widowed landlady. Shareholder of Planet Express.','I, Roommate');
insert into Futurama values('Michelle','Kath Soucie/Sarah Silverman','Former girlfriend of Fry, from 20th century. Later freezes herself until 30th century.','Space Pilot 3000');
insert into Futurama values('Morbo the Annihillator','Maurice LaMarche','Co-anchor of √2 News, with Linda. An advance scout, harvesting information for a forthcoming alien invasion','A Big Piece of Garbage');
insert into Futurama values('Joey Mousepad','John DiMaggio','A member of the Robot Mafia, who wears a mouse and mousepad around his neck.','Bender Gets Made');
insert into Futurama values('Randy Munchnik','John DiMaggio','A stereotypical homosexual man, who owns a jewellery shop.','I, Roommate');
insert into Futurama values('Richard Nixons Head','Billy West','The head of Richard Nixon. Former President of the United States of America. Now incumbent President of Earth.','Space Pilot 3000');
insert into Futurama values('Mr. Panucci','John DiMaggio','Owner of "Panuccis Pizza" and the former boss of Fry, in the 20th century.','Space Pilot 3000');
insert into Futurama values('Pazuzu','David Herman','A large gargoyle, formerly owned by Professor Farnsworth. Occasionally appears to rescue Farnsworth in urgent situations.','Teenage Mutant Leelas Hurdles');
insert into Futurama values('Petunia','Tress MacNeille','An elderly and promiscuous woman from Nutley, New Jersey.','Put Your Head on My Shoulders');
insert into Futurama values('Reverend Lionel Preacherbot','Phil LaMarr','Robot minister of the Temple of Robotology.','Hell Is Other Robots');
insert into Futurama values('Roberto','David Herman','Criminally insane, psychotic robot. Obsessed with stabbing people in different places with different objects.','Insane in the Mainframe');
insert into Futurama values('Robot Devil','Dan Castellaneta/Maurice LaMarche','Robotic personification of the devil, and ruler of Robot Hell.','Hell Is Other Robots');
insert into Futurama values('Robot Santa','John Goodman/John DiMaggio','Robotic personification of Santa Claus, designed to give out presents to those it deems "good". Invariably judges everyone except Zoidberg as "naughty" due to a programming error.','Xmas Story');
insert into Futurama values('Sal','John DiMaggio','Surly and overweight blue-collar worker. Occupies various menial jobs and positions.','The Series Has Landed');
insert into Futurama values('Scruffy','David Herman','Janitor at Planet Express.','A Fishful of Dollars');
insert into Futurama values('Barbados Slim','John DiMaggio','LaBarbara Conrads former husband, and Hermes rival. Only athlete to win gold medals in both limbo and sex.','Bend Her');
insert into Futurama values('Smitty','Billy West','A human policeman, partnered with URL, a robot.','Space Pilot 3000');
insert into Futurama values('Bubblegum Tate','Phil LaMarr','Renowned physicist and leader of the Harlem Globetrotters from the Globetrotter homeworld.','Time Keeps on Slippin');
insert into Futurama values('Tinny Tim','Tress MacNeille','Robotic personification of an orphan. Suffers frequent misfortune.','Space Pilot 3000');
insert into Futurama values('Turanga Morris','David Herman','Leelas father. Lives in the sewers, due to being a mutant.','I Second That Emotion');
insert into Futurama values('Turanga Munda','Tress MacNeille','Leelas mother. Lives in the sewers, due to being a mutant.','I Second That Emotion');
insert into Futurama values('URL','John DiMaggio','Pronounced as "Earl." A robot policeman, partnered with Smitty, a human.','Space Pilot 3000');
insert into Futurama values('Warden Vogel','David Herman','Grade 135 Bureaucrat, and warden of the Cookieville Minimum Security Orphanarium.','The Cyber House Rules');
insert into Futurama values('Dr. Ogden Wernstrom','David Herman','Professor Farnsworths rival and former student.','A Big Piece of Garbage');
insert into Futurama values('Inez Wong','Lauren Tom','Mother of Amy Wong, and wife of Leo Wong. Wealthy owner of Western Hemisphere of Mars.','A Flight to Remember');
insert into Futurama values('Leo Wong','Billy West','Father of Amy Wong, and husband of Inez Wong. Wealthy owner of Western Hemisphere of Mars. Main antagonist of Into the Wild Green Yonder','A Flight to Remember');

select f1.name, f2.name, f1.voiced_by
from Futurama f1, Futurama f2
where f1.voiced_by = f2.voiced_by;